### ISSUE TITLE
Manual benchmark docs need to align with required arguments for train.py (previously "Is device-type needed for local run?")

### ISSUE THREAD

**Issue by ruizhuanguw** [microsoft/lightgbm-benchmark#106]
"device_type" is a required argument for train script. However, it seems not needed for local run and the tutorial at https://microsoft.github.io/lightgbm-benchmark/run/manual-benchmark/ does not provide the argument.

**Comment by jfomhover** [comment]
The manual benchmark docs need to be updated to reflect the latest changes in this train.py script.

device_type could be optional, but it's important to leave it as you could actually run "locally" from a VM with gpus :)
