### ISSUE TITLE
Generate TB of synthetic data to test distributed lightgbm

### ISSUE THREAD

**Issue by jfomhover** [microsoft/lightgbm-benchmark#11]
Current implementation using sklearn `make_classification` or `make_regression` generates all data in memory. We'd like to produce data that cannot fit in memory, in order to test scalability, multi-node, etc.

Goal is to create a duplicate of `src/scripts/data_processing/generate_data/generate.py` to allow for the production of "any" size of data, in particular in the TB order of magnitude. This will be validated by running LightGBM distributed training.

The reason we can't naively use multiple calls of `make_regression` is because when sklearn produces that data, it creates a random fake regression problem and generates data accordingly. If you call that function multiple times, you will obtain distinct datasets having distinct regression problems.

Two solutions:
- modify the current behavior of sklearn to allow for reusing the coefs generated by a previous call.
- create a new data generation scheme for our purpose.

## Learning Goals

By working on this project you'll be able to learn:
- how to write components and pipelines for AzureML (component sdk + shrike)
- how to run LightGBM distributed training

## Expected Deliverable:

To complete this task, you need to deliver:
- 1 working python script to generate large quantity of data
- a successful run of the lightgbm distributed training pipeline

### Prepare for coding

1. Follow the [installation process](https://microsoft.github.io/lightgbm-benchmark/run/install/), please [report any issue](https://github.com/microsoft/lightgbm-benchmark/issues) you meet, that will help!
2. Clone this repo, create your own branch `username/synthetictbdata` (or something) for your own work (commit often!).
3. Copy `src/scripts/data_processing/generate_data/` into another subfolder in `data_processing/large_data_generate`.

### Local development

Feel free to start working on a local python script. Once you have the good behavior, implementing it in AzureML should be straightforward (see following sections).

Here's a couple of contraints we'll ask you to follow:
- create your script as a class that inherits from `RunnableScript`
- use proper argument parsing using argparse (see `get_arg_parser()` method)
- keep reporting some metrics on the data you're generating (see example from `generate_data/`)

#### Component specification

1. First, unit tests. Edit `tests/aml/test_components.py` and watch for the list of components. Add the relative path to your component spec in this list.

    You can test your component by running
    ```bash
    pytest tests/aml/test_components.py -v -k large_data_generate
    ```

2. Edit the file `spec.yaml` in the directory of your component (copied from sample) and align its arguments with the expected arguments of your component until you pass the unit tests.

#### Integration in the data generation pipeline

WORK IN PROGRESS

**Comment by ulfk-ms** [comment]
Simple proposal: breaking down the dataset into chunks that fit into memory and generating/writing them sequentially. An alternative might be to be able to generate multiple smaller datasets and combine them (vertically and/or horizontally) when training/inferencing.

**Comment by jfomhover** [comment]
I'm curious if we should either:
1) generate one big data file (appending)
2) generate partitioned data files

approach 1 could be closer to actual prod scenario, and would point out the bottlenecks and issues using lightgbm inferencing or training on large dataasets.

**Comment by jfomhover** [comment]
It would be awesome to use Ray for this https://www.ray.io so data generation could parallelize and be scalable.
