### ISSUE TITLE
Support testing multiple parameter sets

### ISSUE THREAD

**Issue by ulfk-ms** [microsoft/lightgbm-benchmark#59]
- allow definition of multiple parameter sets
- provide default list of parameter sets to test
- potentially use sweep
- provide informative analysis
-

**Comment by jfomhover** [comment]
This PR #94  introduces a mechanism where one can define a set of "Reference" parameters for training, then "variants" that just override specific parameters.

The whole thing makes benchmarking multiple training parameters much easier.
